version: '3.8'
services:
  app:
    build: .
    image: productos-app:latest
    container_name: productos-app
    ports:
      - "8080:8080"
    environment:
      - APP_NAME=${APP_NAME}
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DRIVER=${DB_DRIVER}
      - JPA_DDL_AUTO=${JPA_DDL_AUTO}
      - JPA_SHOW_SQL=${JPA_SHOW_SQL}
      - SERVER_PORT=${SERVER_PORT}
    restart: unless-stopped