version: '3.8'
services:
  app:
    build: .
    image: productos-app:latest
    container_name: productos-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: productos-db
    environment:
      MYSQL_DATABASE: productosdb
      MYSQL_ROOT_PASSWORD: liseth
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
